version: '3'

services:
  bot:
    build: .
    env_file: /root/bot/aiogram-google-mongo-client/.env
    image: telegram_access_bot:latest
    container_name: telegram_bot
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017

  mongo:
    image: "mongo"
    container_name: mongo_db
    environment:
      #Use these credentials to initialize root user to enable -auth automatically
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - "./mongo_client/mongo_init/:/docker-entrypoint-initdb.d/"
    command: mongod

volumes:
  mongodata:

