version: '3'

services:
  bot:
    build: .
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: ${MONGO_PORT}

  mongo:
    image: "mongo"
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
