version: '3'

services:
  bot:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongo

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
