version: '3'

services:
  bot:
    build: .
    env_file: ./.env
    image: telegram_access_bot:latest
    container_name: telegram_bot
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017

  mongo:
    image: "mongo"
    container_name: mongo_db
    env_file: ./.env
    environment:
      #Use these credentials to initialize root user to enable -auth automatically
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=admin
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - "./client/mongo_client/mongo_init/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro"

volumes:
  mongodata:

