name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: connect to Kamatera using SSH and run bash command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.KAMATERA_SERVER_IP }}
        username: ${{ secrets.KAMATERA_USERNAME }}
        password: ${{ secrets.KAMATERA_PASSWORD }}
        script: |
          echo "Starting deployment process..."
          echo "Current directory is $(pwd)"
          REPO_DIR="/root/bot/aiogram-google-mongo-client"
          if [ -d "$REPO_DIR" ]; then
            echo "Repository exists. Updating existing repository..."
            cd "$REPO_DIR"
            git fetch
            git reset --hard origin/production
            git clean -fd
          else 
            echo "Cloning the repository for the first time..."
            cd /root/bot
            git clone -b production ${{ secrets.REPOSITORY_URL }}
            cd "$REPO_DIR" 
          fi
          echo "Exposing environment variables..."
          export PRODUCTION_BOT_TOKEN=${{ secrets.PRODUCTION_BOT_TOKEN }}
          echo "PRODUCTION_BOT_TOKEN length: ${#PRODUCTION_BOT_TOKEN}"
          export DEVELOPMENT_BOT_TOKEN=${{ secrets.DEVELOPMENT_BOT_TOKEN }}
          echo "DEVELOPMENT_BOT_TOKEN length: ${#DEVELOPMENT_BOT_TOKEN}"
          export AUTHOR_CHAT_ID=${{ secrets.AUTHOR_CHAT_ID }}
          echo "AUTHOR_CHAT_ID length: ${#AUTHOR_CHAT_ID}"
          export GUIDE_LINK=${{ secrets.GUIDE_LINK }}
          echo "GUIDE_LINK length: ${#GUIDE_LINK}"
          export WEB_CONTENT_TABLE_LINK=${{ secrets.WEB_CONTENT_TABLE_LINK }}
          echo "WEB_CONTENT_TABLE_LINK length: ${#WEB_CONTENT_TABLE_LINK}"
          export WEB_AI_CONTENT_TABLE_LINK=${{ secrets.WEB_AI_CONTENT_TABLE_LINK }}
          echo "WEB_AI_CONTENT_TABLE_LINK length: ${#WEB_AI_CONTENT_TABLE_LINK}"
          export SEO_CONTENT_TABLE_LINK=${{ secrets.SEO_CONTENT_TABLE_LINK }}
          echo "SEO_CONTENT_TABLE_LINK length: ${#SEO_CONTENT_TABLE_LINK}"
          export BACKUP_TABLE_LINK=${{ secrets.BACKUP_TABLE_LINK }}
          echo "BACKUP_TABLE_LINK length: ${#BACKUP_TABLE_LINK}"
          export DUPLICHEKER_TOKEN=${{ secrets.DUPLICHEKER_TOKEN }}
          echo "DUPLICHEKER_TOKEN length: ${#DUPLICHEKER_TOKEN}"
          export WEB_CONTENT_CHAT_ID=${{ secrets.WEB_CONTENT_CHAT_ID }}
          echo "WEB_CONTENT_CHAT_ID length: ${#WEB_CONTENT_CHAT_ID}"
          echo "Running bash script..."
          bash deploy.sh production
