name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: connect to Kamatera using SSH and run bash command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.KAMATERA_SERVER_IP }}
        username: ${{ secrets.KAMATERA_USERNAME }}
        password: ${{ secrets.KAMATERA_PASSWORD }}
        script: |
          echo "Starting deployment process..."
          echo "Current directory is $(pwd)"
          echo "Entering the directory..."
          cd bot
          echo "Listing contents of repository:"
          ls -a
          echo "Cloning the repository..."
          git clone ${{ secrets.REPOSITORY_URL }}
          echo "Entering the repository..."
          cd aiogram-google-mongo-client
          echo "Running bash script..."
          bash deploy.sh production
