name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: connect to Kamatera using SSH and run bash command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.KAMATERA_SERVER_IP }}
        username: ${{ secrets.KAMATERA_USERNAME }}
        password: ${{ secrets.KAMATERA_PASSWORD }}
        envs: |
          PRODUCTION_BOT_TOKEN=${{ secrets.PRODUCTION_BOT_TOKEN }},
          DEVELOPMENT_BOT_TOKEN=${{ secrets.DEVELOPMENT_BOT_TOKEN }},
          AUTHOR_CHAT_ID=${{ secrets.AUTHOR_CHAT_ID }},
          GUIDE_LINK=${{ secrets.GUIDE_LINK }},
          WEB_CONTENT_TABLE_LINK=${{ secrets.WEB_CONTENT_TABLE_LINK }},
          WEB_AI_CONTENT_TABLE_LINK=${{ secrets.WEB_AI_CONTENT_TABLE_LINK }},
          SEO_CONTENT_TABLE_LINK=${{ secrets.SEO_CONTENT_TABLE_LINK }},
          BACKUP_TABLE_LINK=${{ secrets.BACKUP_TABLE_LINK }},
          DUPLICHEKER_TOKEN=${{ secrets.DUPLICHEKER_TOKEN }},
          WEB_CONTENT_CHAT_ID=${{ secrets.WEB_CONTENT_CHAT_ID }}
        script: |
          echo "Checking if environment variables are set..."
          if [ -z "$PRODUCTION_BOT_TOKEN" ]; then echo "PRODUCTION_BOT_TOKEN is not set"; else echo "PRODUCTION_BOT_TOKEN is set"; fi
          if [ -z "$DEVELOPMENT_BOT_TOKEN" ]; then echo "DEVELOPMENT_BOT_TOKEN is not set"; else echo "DEVELOPMENT_BOT_TOKEN is set"; fi
          echo "Starting deployment process..."
          REPO_DIR="/root/bot/aiogram-google-mongo-client"
          if [ -d "$REPO_DIR" ]; then
            echo "Repository exists. Updating existing repository..."
            cd "$REPO_DIR"
            git fetch
            git reset --hard origin/production
            git clean -fd
          else 
            echo "Cloning the repository for the first time..."
            cd /root/bot
            git clone -b production ${{ secrets.REPOSITORY_URL }}
            cd "$REPO_DIR" 
          fi
          echo "Running bash script..."
          bash deploy.sh production
