name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: connect to Kamatera using SSH and run bash command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.KAMATERA_SERVER_IP }}
        username: ${{ secrets.KAMATERA_USERNAME }}
        password: ${{ secrets.KAMATERA_PASSWORD }}
        script: |
          echo "Starting deployment process..."
          echo "Current directory is $(pwd)"
          REPO_DIR="/root/bot/aiogram-google-mongo-client"
          if [ -d "$REPO_DIR" ]; then
            echo "Repository exists. Updating existing repository..."
            cd "$REPO_DIR"
            git fetch
            git reset --hard origin/production
            git clean -fd
          else 
            echo "Cloning the repository for the first time..."
            cd bot
            git clone ${{ secrets.REPOSITORY_URL }}
          echo "Entering the repository..."
          cd aiogram-google-mongo-client
          echo "Exposing environment variables..."
          export PRODUCTION_BOT_TOKEN=${{ secrets.PRODUCTION_BOT_TOKEN }}
          export DEVELOPMENT_BOT_TOKEN=${{ secrets.DEVELOPMENT_BOT_TOKEN }}
          export AUTHOR_CHAT_ID=${{ secrets.AUTHOR_CHAT_ID }}
          export GUIDE_LINK=${{ secrets.GUIDE_LINK }}
          export WEB_CONTENT_TABLE_LINK=${{ secrets.WEB_CONTENT_TABLE_LINK }}
          export WEB_AI_CONTENT_TABLE_LINK=${{ secrets.WEB_AI_CONTENT_TABLE_LINK }}
          export SEO_CONTENT_TABLE_LINK=${{ secrets.SEO_CONTENT_TABLE_LINK }}
          export BACKUP_TABLE_LINK=${{ secrets.BACKUP_TABLE_LINK }}
          export DUPLICHEKER_TOKEN=${{ secrets.DUPLICHEKER_TOKEN }}
          export WEB_CONTENT_CHAT_ID=${{ secrets.WEB_CONTENT_CHAT_ID }}
          echo "Running bash script..."
          bash deploy.sh production
